name: test

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'LICENSE'
      - 'README*'
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - 'README*'

jobs:
  skip:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skip job"

  before:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "not contains '[skip ci]'"

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest
          # - macOS-latest
        nim-version:
          - stable
          - 1.4.0
    needs: before
    steps:
      - uses: actions/checkout@v1
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}
      - run: nimble test -Y
      - run: nimble install -Y
